version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.postgres
    ports:
      - "5432:5432"
  keycloak:
    image: jboss/keycloak:latest
    env_file:
      - .env.keycloak
    ports:
      - "8080:8080"
    depends_on:
      - postgres
